[package]
name = "timeknight"
version = "0.1.0"
edition = "2021"

[dependencies]
structopt="0.3.25"
log = "0.4.0"
env_logger = "0.9.0"
termion = "1.5"
tui = { version = "^0", default-features = false, features = ["termion"] }
